name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: huggingface-cli login --token $HF_TOKEN

      - name: Configure Git user
        run: |
          git config --global user.name "Zaeem-Muhammad"
          git config --global user.email "muhammadzaeem1026@gmail.com"

      - name: Check for changes and push
        run: |
          git lfs install
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update model"
            git push https://huggingface.co/spaces/muhammadzaeem/Mlops-Assignment4.git
          else
            echo "No changes to commit"
          fi
