name: CI/CD for Hugging Face Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install huggingface_hub

      - name: Log in to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          huggingface-cli login --token $HF_TOKEN

      - name: Deploy to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          if [ ! -d "Mlops-Assignment4" ]; then
            git clone https://huggingface.co/spaces/muhammadzaeem/Mlops-Assignment4.git
          else
            cd Mlops-Assignment4
            git pull origin main
          fi
          cd Mlops-Assignment4
          git config --global user.email "muhammadzaeem1026@gmail.com"
          git config --global user.name "Zaeem-Muhammad"
          git add .
          git commit -m "Deploy updated code"
          git push origin main
